# Generated by Django 4.1.4 on 2022-12-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=35)),
                ('company_startdate', models.DateField(blank=True, null=True)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('city', models.CharField(max_length=30, null=True)),
                ('adhar_number', models.CharField(max_length=50)),
                ('gst_number', models.CharField(max_length=50)),
                ('is_varified', models.BooleanField(default=False)),
                ('is_bank_varified', models.BooleanField(default=False)),
                ('is_bussiness_card', models.BooleanField(default=False)),
            ],
        ),
    ]
