# Generated by Django 4.1.3 on 2022-12-08 11:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('vahak_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=55)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=17, null=True, region=None, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='phone number')),
                ('otp', models.CharField(blank=True, max_length=9, null=True)),
                ('referral_code', models.CharField(blank=True, max_length=20, null=True)),
                ('otp_genarate_time', models.DateTimeField()),
                ('is_phone_verified', models.BooleanField(default=False, help_text='Users mobile number is verfied with otp', max_length=20)),
                ('is_user_verified', models.BooleanField(default=False, help_text='Aadhar and gst verified user', max_length=20)),
                ('is_bank_varified', models.BooleanField(default=False, help_text='User Added his account details', max_length=20)),
                ('is_busssiness_card', models.BooleanField(default=False, help_text='User created business card', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_start_date', models.PositiveSmallIntegerField(blank=True, help_text='Starting year of company', null=True)),
                ('company_bio', models.TextField()),
                ('city', models.CharField(blank=True, max_length=40, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images')),
                ('cover_images', models.ImageField(blank=True, upload_to='cover_images')),
                ('routes', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='vahak_api.routes')),
                ('user', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='vahak_api.user')),
            ],
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
