# Generated by Django 4.1.3 on 2022-12-09 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vahak_api', '0003_remove_routes_name_routes_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Businesscardmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person_name', models.CharField(max_length=30)),
                ('Designation', models.CharField(max_length=30)),
                ('Alternative_contact', models.CharField(blank=True, max_length=30, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('Bussiness_Address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicalmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicle_name', models.CharField(max_length=30)),
                ('Vehicle_load_capacity', models.CharField(max_length=30)),
                ('Vehicle_Type', models.CharField(max_length=30)),
                ('Is_Tyres_defined', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attachnewlorry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserVehicle_number', models.CharField(max_length=50)),
                ('Current_location', models.CharField(max_length=35)),
                ('Permit', models.CharField(max_length=50)),
                ('Is_all_permit', models.BooleanField(blank=True, null=True)),
                ('Is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('Is_Rc_verfied', models.BooleanField(blank=True, default=False, null=True)),
                ('Vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vahak_api.vehicalmodel')),
            ],
        ),
    ]
