# Generated by Django 4.1.3 on 2022-12-09 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vahak_api', '0004_businesscardmodel_vehicalmodel_attachnewlorry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Businesscardmodel',
            new_name='Businesscard',
        ),
    ]
